<!-- build:js(src/main/webapp) /js/vender.js -->
<script type="text/javascript" src="/js/lib/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/js/lib/sea.js"></script>
<!-- endbuild -->
<@DevelopOnly>
    <script type="text/javascript">
    seajs.config({
        base : '/js'
    });
    </script>
</@DevelopOnly>
<#-- common js file, generated by spm -->
<script type="text/javascript" src="/js/common.js"></script>
